"""
logger.py

Logs inference metadata generated by
the SignSync AI Engine.
"""

from datetime import datetime


class InferenceLogger:
    """
    Logs inference information.
    """

    def __init__(self):

        self.logs = []

    def log(
        self,
        prediction,
        confidence,
        model_version,
        inference_time_ms,
        status
    ):
        """
        Store inference metadata.
        """

        record = {

            "timestamp": datetime.now().strftime(
                "%Y-%m-%d %H:%M:%S"
            ),

            "prediction": prediction,

            "confidence": round(
                float(confidence),
                4
            ),

            "model_version": model_version,

            "inference_time_ms": round(
                float(inference_time_ms),
                4
            ),

            "status": status

        }

        self.logs.append(record)

        print("\n========== Inference Log ==========")

        print(f"Time          : {record['timestamp']}")
        print(f"Prediction    : {record['prediction']}")
        print(f"Confidence    : {record['confidence']}")
        print(f"Model Version : {record['model_version']}")
        print(f"Inference(ms) : {record['inference_time_ms']}")
        print(f"Status        : {record['status']}")

        print("===================================\n")

        return record

    def get_logs(self):
        """
        Return all inference logs.
        """

        return self.logs